[theme]
primaryColor = "#FFFFFF"                   # White text for contrast
backgroundColor = "#B71C1C"                # Deep red background
secondaryBackgroundColor = "#E53935"       # Lighter red for containers/widgets
textColor = "#FFFFFF"                      # White text
font = "sans serif"
