[theme]
primaryColor = "#B71C1C"              # Red
backgroundColor = "#FFFFFF"           # White
secondaryBackgroundColor = "#FDECEC"  # Light pink/red tint
textColor = "#000000"                 # Black
font = "sans serif"

             # Other options: "serif", "monospace"
