[theme]
primaryColor = "#FF0000"            # Bold red for buttons, sliders, etc.
backgroundColor = "#FFFFFF"         # White background
secondaryBackgroundColor = "#FFF1F1"  # Very light red (pinkish) for containers
textColor = "#000000"               # Black text
font = "sans serif"
